### ISSUE TITLE
bug: Can't send message with non default parameters

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-broker#4]
While testing plugin for Stash I encountered weird behaviour
I can't send messages when creating sender with parameters different form default

```
new TraceyRabbitMQSenderImpl("192.168.99.100", "guest", "guest", 32751)
```

I'm sure that it is possible to connect to this configuration because i tested that with the python scripts. After I tweaked my docker container to be on localhost:5672 everything worked as expected

I was about to test it using cli version of sender but cound't get it to work

**Comment by MadsNielsen** [comment]
@Andrey9kin it should work with the newest version. 

`new TraceyRabbitMQSenderImpl("192.168.99.100", "guest", "guest", 32751).send("Hi tracey", "tracey")`

**Comment by MadsNielsen** [comment]
And you can check the following also: 

```
TraceyRabbitMQSenderImpl impl = new TraceyRabbitMQSenderImpl("192.168.99.100", "guest", "guest", 32751).configure();
System.out.println(impl);
```

If it was configured correctly the printout shoud say:
`guest@192.168.99.100:32751`
