### ISSUE TITLE
suggestion: provide possibility to define a format of the rounding key

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-broker#5]
Today we rely on an assumption that message we receive will be an Eiffel-like message, i.e. will contain type property which is not necessarily true as well as creates a dependency to Eiffel.

Suggestion: to investigate possibility configure routing key format through the configuration file. Similarly, how we about to do with the arbitrary variable injection in the Jenkins plugin, i.e. allow users to query for certain fields and then arrange query results in a particular order

We also need to check how we determine name for the exchange since we might have a binding there

**Comment by MadsNielsen** [comment]
Great idea...

We could make a section in the config file. 

```
routing {
  tracey.event.${event_type}
  ${domain}.event   
}
```

We could then expose a set of pre-set replacement patterns, event type for Eiffel, and expand environement variables. 

Something like that in mind @Andrey9kin

**Comment by Andrey9kin** [comment]
@MadsNielsen I would rather avoid pre-set replace patterns to stay generic and do like we did in Jenkins plugin Praqma/tracey-jenkins-trigger-plugin#14, i.e. allow the user to set her own bindings and then use them to define routing key. However, in general, yes, this is what I'm thinking about.
