### ISSUE TITLE
Add possibility to provide additional metadata

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-broker#6]
Find a way how to extend interface definition so we can send additional routing and messaging metadata

In case of RabbitMQ such metadata should include:
- headers
- sending mode (persistent/non-persistent)
- routing key (not sure how it is passed in today but probably it makes sense to send it within this new structure)

DoD:
- Update TraceyBroker interface definition with possibility to provide additional metadata along side with the payload
- Implement corresponding data structures in RabbitMQ implementation of TraceyBroker
- Cover updates with unit tests
- documentation update

**Comment by alexsedova** [comment]
Push current changes to issue6 branch. There is new class TraceyMessageData contains fields headers, deliveryMode and routingKey. Also, TraceySender updated with new argument as well as all class implementations. I added new unit test to DispatcherTest.
If we will use these changes we have to update all uses of TraceyRabbitMQSenderImpl in all projects.

**Comment by Andrey9kin** [comment]
@alexsedova It looks good.
Few things to consider:
- Make sure that it is possible to send all types of data supported by RabbitMQ (string, int, boolean, list), i.e. check that in unit tests
- Make sure that user can't pass unsupported data type
- How about to rename TraceyMessageData to RoutingInfo? I think we should follow your suggestion and destination (exchange name) and exchange type to that data structure. Payload field will stay as a string so call would look like send(RoutingInfo destination, String payload)

You probably will notice that TraceyEiffelMessageDispatcher.java contains certain hardcodes and not really using exchange type as it should. Ignore it for now. We will address that in scope of issue #7

**Comment by Andrey9kin** [comment]
Updated DoD - make sure to update README.md after interface change
